backend:
  name: git-gateway
  # repo: ndom91/newtelco-gatsby-netlify
  # branch: master
  # site_domain: https://newtelco-gatsby.netlify.com/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"
show_preview_links: true
logo_url: "https://imgur.com/f3x0X6p.png"
slug:
  clean_accents: true
  sanitize_replacements: "_"

collections:
  #Pages (English)
  - name: "pages-en" # Used in routes, e.g., /admin/collections/blog
    label: "Pages (EN)" # Used in the UI
    label_singular: "Page (EN)"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: frontmatter
    summary: "{{title}} (Updated: {{commit_date}})"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  #Pages (German)
  - name: "pages-de" # Used in routes, e.g., /admin/collections/blog
    label: "Pages (DE)" # Used in the UI
    label_singular: "Page (DE)"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "de.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  #Pages (Russian)
  - name: "pages-ru" # Used in routes, e.g., /admin/collections/blog
    label: "Pages (RU)" # Used in the UI
    label_singular: "Page (RU)"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "ru.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }

  #Products (English)
  - name: "products-en" # Used in routes, e.g., /admin/collections/blog
    label: "Products (EN)" # Used in the UI
    label_singular: "Product (EN)"
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Products (German)
  - name: "products-de" # Used in routes, e.g., /admin/collections/blog
    label: "Products (DE)" # Used in the UI
    label_singular: "Product (DE)"
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "de.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Products (Russian)
  - name: "products-ru" # Used in routes, e.g., /admin/collections/blog
    label: "Products (RU)" # Used in the UI
    label_singular: "Product (RU)"
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "ru.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Services (English)
  - name: "services-en" # Used in routes, e.g., /admin/collections/blog
    label: "Services (EN)" # Used in the UI
    label_singular: "Service (EN)"
    folder: "content/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Services (German)
  - name: "services-de" # Used in routes, e.g., /admin/collections/blog
    label: "Services (DE)" # Used in the UI
    label_singular: "Service (DE)"
    folder: "content/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "de.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Services (Russian)
  - name: "services-ru" # Used in routes, e.g., /admin/collections/blog
    label: "Services (RU)" # Used in the UI
    label_singular: "Service (RU)"
    folder: "content/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "ru.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Locations (English)
  - name: "locations-en" # Used in routes, e.g., /admin/collections/blog
    label: "Locations (EN)" # Used in the UI
    label_singular: "Location (EN)"
    folder: "content/location" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "en.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Description", name: "desc", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Locations (German)
  - name: "locations-de" # Used in routes, e.g., /admin/collections/blog
    label: "Locations (DE)" # Used in the UI
    label_singular: "Location (DE)"
    folder: "content/location" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "de.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Description", name: "desc", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  #Locations (Russian)
  - name: "locations-ru" # Used in routes, e.g., /admin/collections/blog
    label: "Locations (RU)" # Used in the UI
    label_singular: "Location (RU)"
    folder: "content/location" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "ru.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - { label: "isSection", name: "section", widget: "hidden", default: true }
      - { label: "Short", name: "short", widget: "markdown" }
      - { label: "Description", name: "desc", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Testimonials
  - name: "testimonials" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonials" # Used in the UI
    label_singular: "Testimonial"
    folder: "content/testimonials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md"
    format: frontmatter
    summary: "{{company}} (Updated: {{commit_date}})"
    fields: # The fields for each document, usually in front matter
      - { label: "isPage", name: "page", widget: "hidden", default: false }
      - {
          label: "isSection",
          name: "section",
          widget: "hidden",
          default: false,
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  # Team Members
  - name: "teammembers"
    label: "Team Members"
    label_singular: "Teammember"
    files:
      - label: "Members"
        name: "members"
        file: "content/teamMembers.json"
        fields:
          - label: Members
            name: Members
            widget: list
            fields:
              - { label: "Name", name: name, widget: string }
              - { label: "Email", name: email, widget: string }
              - {
                  label: "Picture",
                  name: picture,
                  widget: image,
                  allow_multiple: false,
                  optional: true,
                }
              - label: "Department"
                name: "dept"
                widget: "select"
                options:
                  - { label: "Sales", value: "sales" }
                  - { label: "Marketing", value: "marketing" }
                  - { label: "Billing", value: "billing" }
                  - { label: "Engineering", value: "engineering" }
                  - { label: "Order", value: "order" }
                  - { label: "Management", value: "management" }
